version: '3.8'

services:
  exif-ai-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - EXIF_AI_PROVIDER=ollama
      - EXIF_AI_MODEL=llama3.2-vision
      - EXIF_AI_TASKS=description,tag
      - EXIF_AI_VERBOSE=false
    # Mount your environment file
    env_file:
      - .env
    # Optional: Mount volume for persistent data
    # volumes:
    #   - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Optional: Include Ollama service for local AI processing
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Uncomment if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
